-- Programa que invierte la palabra y la copia al final con alfabeto completo (a–z)
DELETE FROM alfabeto;
INSERT INTO alfabeto (simbolo) VALUES
('a'),
('b'),
('c'),
('d'),
('e'),
('f'),
('g'),
('h'),
('i'),
('j'),
('k'),
('l'),
('m'),
('n'),
('o'),
('p'),
('q'),
('r'),
('s'),
('t'),
('u'),
('v'),
('w'),
('x'),
('y'),
('z'),
('X'),
('B');

DELETE FROM programa;

--MOVERSE HASTA EL FINAL LA PRIMERA VEZ;
INSERT INTO programa VALUES ('q0', 'a', 'q0', 'a', 'R');
INSERT INTO programa VALUES ('q0', 'b', 'q0', 'b', 'R');
INSERT INTO programa VALUES ('q0', 'c', 'q0', 'c', 'R');
INSERT INTO programa VALUES ('q0', 'd', 'q0', 'd', 'R');
INSERT INTO programa VALUES ('q0', 'e', 'q0', 'e', 'R');
INSERT INTO programa VALUES ('q0', 'f', 'q0', 'f', 'R');
INSERT INTO programa VALUES ('q0', 'g', 'q0', 'g', 'R');
INSERT INTO programa VALUES ('q0', 'h', 'q0', 'h', 'R');
INSERT INTO programa VALUES ('q0', 'i', 'q0', 'i', 'R');
INSERT INTO programa VALUES ('q0', 'j', 'q0', 'j', 'R');
INSERT INTO programa VALUES ('q0', 'k', 'q0', 'k', 'R');
INSERT INTO programa VALUES ('q0', 'l', 'q0', 'l', 'R');
INSERT INTO programa VALUES ('q0', 'm', 'q0', 'm', 'R');
INSERT INTO programa VALUES ('q0', 'n', 'q0', 'n', 'R');
INSERT INTO programa VALUES ('q0', 'o', 'q0', 'o', 'R');
INSERT INTO programa VALUES ('q0', 'p', 'q0', 'p', 'R');
INSERT INTO programa VALUES ('q0', 'q', 'q0', 'q', 'R');
INSERT INTO programa VALUES ('q0', 'r', 'q0', 'r', 'R');
INSERT INTO programa VALUES ('q0', 's', 'q0', 's', 'R');
INSERT INTO programa VALUES ('q0', 't', 'q0', 't', 'R');
INSERT INTO programa VALUES ('q0', 'u', 'q0', 'u', 'R');
INSERT INTO programa VALUES ('q0', 'v', 'q0', 'v', 'R');
INSERT INTO programa VALUES ('q0', 'w', 'q0', 'w', 'R');
INSERT INTO programa VALUES ('q0', 'x', 'q0', 'x', 'R');
INSERT INTO programa VALUES ('q0', 'y', 'q0', 'y', 'R');
INSERT INTO programa VALUES ('q0', 'z', 'q0', 'z', 'R');
INSERT INTO programa VALUES ('q0', 'B', 'load', 'B', 'L');

--AGARRA EL PRIMER VALOR A COPIAR (ULTIMO CARACTER);
INSERT INTO programa VALUES ('load', 'a', 'load_a', 'X', 'R');
INSERT INTO programa VALUES ('load', 'b', 'load_b', 'X', 'R');
INSERT INTO programa VALUES ('load', 'c', 'load_c', 'X', 'R');
INSERT INTO programa VALUES ('load', 'd', 'load_d', 'X', 'R');
INSERT INTO programa VALUES ('load', 'e', 'load_e', 'X', 'R');
INSERT INTO programa VALUES ('load', 'f', 'load_f', 'X', 'R');
INSERT INTO programa VALUES ('load', 'g', 'load_g', 'X', 'R');
INSERT INTO programa VALUES ('load', 'h', 'load_h', 'X', 'R');
INSERT INTO programa VALUES ('load', 'i', 'load_i', 'X', 'R');
INSERT INTO programa VALUES ('load', 'j', 'load_j', 'X', 'R');
INSERT INTO programa VALUES ('load', 'k', 'load_k', 'X', 'R');
INSERT INTO programa VALUES ('load', 'l', 'load_l', 'X', 'R');
INSERT INTO programa VALUES ('load', 'm', 'load_m', 'X', 'R');
INSERT INTO programa VALUES ('load', 'n', 'load_n', 'X', 'R');
INSERT INTO programa VALUES ('load', 'o', 'load_o', 'X', 'R');
INSERT INTO programa VALUES ('load', 'p', 'load_p', 'X', 'R');
INSERT INTO programa VALUES ('load', 'q', 'load_q', 'X', 'R');
INSERT INTO programa VALUES ('load', 'r', 'load_r', 'X', 'R');
INSERT INTO programa VALUES ('load', 's', 'load_s', 'X', 'R');
INSERT INTO programa VALUES ('load', 't', 'load_t', 'X', 'R');
INSERT INTO programa VALUES ('load', 'u', 'load_u', 'X', 'R');
INSERT INTO programa VALUES ('load', 'v', 'load_v', 'X', 'R');
INSERT INTO programa VALUES ('load', 'w', 'load_w', 'X', 'R');
INSERT INTO programa VALUES ('load', 'x', 'load_x', 'X', 'R');
INSERT INTO programa VALUES ('load', 'y', 'load_y', 'X', 'R');
INSERT INTO programa VALUES ('load', 'z', 'load_z', 'X', 'R');
INSERT INTO programa VALUES ('load', 'B', 'finish', 'B', 'L');

--BUSCA EL PRIMER B DISPONIBLE Y PEGA EL VALOR;
INSERT INTO programa VALUES ('load_a', 'a', 'load_a', 'a', 'R');
INSERT INTO programa VALUES ('load_a', 'b', 'load_a', 'b', 'R');
INSERT INTO programa VALUES ('load_a', 'c', 'load_a', 'c', 'R');
INSERT INTO programa VALUES ('load_a', 'd', 'load_a', 'd', 'R');
INSERT INTO programa VALUES ('load_a', 'e', 'load_a', 'e', 'R');
INSERT INTO programa VALUES ('load_a', 'f', 'load_a', 'f', 'R');
INSERT INTO programa VALUES ('load_a', 'g', 'load_a', 'g', 'R');
INSERT INTO programa VALUES ('load_a', 'h', 'load_a', 'h', 'R');
INSERT INTO programa VALUES ('load_a', 'i', 'load_a', 'i', 'R');
INSERT INTO programa VALUES ('load_a', 'j', 'load_a', 'j', 'R');
INSERT INTO programa VALUES ('load_a', 'k', 'load_a', 'k', 'R');
INSERT INTO programa VALUES ('load_a', 'l', 'load_a', 'l', 'R');
INSERT INTO programa VALUES ('load_a', 'm', 'load_a', 'm', 'R');
INSERT INTO programa VALUES ('load_a', 'n', 'load_a', 'n', 'R');
INSERT INTO programa VALUES ('load_a', 'o', 'load_a', 'o', 'R');
INSERT INTO programa VALUES ('load_a', 'p', 'load_a', 'p', 'R');
INSERT INTO programa VALUES ('load_a', 'q', 'load_a', 'q', 'R');
INSERT INTO programa VALUES ('load_a', 'r', 'load_a', 'r', 'R');
INSERT INTO programa VALUES ('load_a', 's', 'load_a', 's', 'R');
INSERT INTO programa VALUES ('load_a', 't', 'load_a', 't', 'R');
INSERT INTO programa VALUES ('load_a', 'u', 'load_a', 'u', 'R');
INSERT INTO programa VALUES ('load_a', 'v', 'load_a', 'v', 'R');
INSERT INTO programa VALUES ('load_a', 'w', 'load_a', 'w', 'R');
INSERT INTO programa VALUES ('load_a', 'x', 'load_a', 'x', 'R');
INSERT INTO programa VALUES ('load_a', 'y', 'load_a', 'y', 'R');
INSERT INTO programa VALUES ('load_a', 'z', 'load_a', 'z', 'R');
INSERT INTO programa VALUES ('load_a', 'X', 'load_a', 'X', 'R');
INSERT INTO programa VALUES ('load_a', 'B', 'search_X', 'a', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_b', 'a', 'load_b', 'a', 'R');
INSERT INTO programa VALUES ('load_b', 'b', 'load_b', 'b', 'R');
INSERT INTO programa VALUES ('load_b', 'c', 'load_b', 'c', 'R');
INSERT INTO programa VALUES ('load_b', 'd', 'load_b', 'd', 'R');
INSERT INTO programa VALUES ('load_b', 'e', 'load_b', 'e', 'R');
INSERT INTO programa VALUES ('load_b', 'f', 'load_b', 'f', 'R');
INSERT INTO programa VALUES ('load_b', 'g', 'load_b', 'g', 'R');
INSERT INTO programa VALUES ('load_b', 'h', 'load_b', 'h', 'R');
INSERT INTO programa VALUES ('load_b', 'i', 'load_b', 'i', 'R');
INSERT INTO programa VALUES ('load_b', 'j', 'load_b', 'j', 'R');
INSERT INTO programa VALUES ('load_b', 'k', 'load_b', 'k', 'R');
INSERT INTO programa VALUES ('load_b', 'l', 'load_b', 'l', 'R');
INSERT INTO programa VALUES ('load_b', 'm', 'load_b', 'm', 'R');
INSERT INTO programa VALUES ('load_b', 'n', 'load_b', 'n', 'R');
INSERT INTO programa VALUES ('load_b', 'o', 'load_b', 'o', 'R');
INSERT INTO programa VALUES ('load_b', 'p', 'load_b', 'p', 'R');
INSERT INTO programa VALUES ('load_b', 'q', 'load_b', 'q', 'R');
INSERT INTO programa VALUES ('load_b', 'r', 'load_b', 'r', 'R');
INSERT INTO programa VALUES ('load_b', 's', 'load_b', 's', 'R');
INSERT INTO programa VALUES ('load_b', 't', 'load_b', 't', 'R');
INSERT INTO programa VALUES ('load_b', 'u', 'load_b', 'u', 'R');
INSERT INTO programa VALUES ('load_b', 'v', 'load_b', 'v', 'R');
INSERT INTO programa VALUES ('load_b', 'w', 'load_b', 'w', 'R');
INSERT INTO programa VALUES ('load_b', 'x', 'load_b', 'x', 'R');
INSERT INTO programa VALUES ('load_b', 'y', 'load_b', 'y', 'R');
INSERT INTO programa VALUES ('load_b', 'z', 'load_b', 'z', 'R');
INSERT INTO programa VALUES ('load_b', 'X', 'load_b', 'X', 'R');
INSERT INTO programa VALUES ('load_b', 'B', 'search_X', 'b', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_c', 'a', 'load_c', 'a', 'R');
INSERT INTO programa VALUES ('load_c', 'b', 'load_c', 'b', 'R');
INSERT INTO programa VALUES ('load_c', 'c', 'load_c', 'c', 'R');
INSERT INTO programa VALUES ('load_c', 'd', 'load_c', 'd', 'R');
INSERT INTO programa VALUES ('load_c', 'e', 'load_c', 'e', 'R');
INSERT INTO programa VALUES ('load_c', 'f', 'load_c', 'f', 'R');
INSERT INTO programa VALUES ('load_c', 'g', 'load_c', 'g', 'R');
INSERT INTO programa VALUES ('load_c', 'h', 'load_c', 'h', 'R');
INSERT INTO programa VALUES ('load_c', 'i', 'load_c', 'i', 'R');
INSERT INTO programa VALUES ('load_c', 'j', 'load_c', 'j', 'R');
INSERT INTO programa VALUES ('load_c', 'k', 'load_c', 'k', 'R');
INSERT INTO programa VALUES ('load_c', 'l', 'load_c', 'l', 'R');
INSERT INTO programa VALUES ('load_c', 'm', 'load_c', 'm', 'R');
INSERT INTO programa VALUES ('load_c', 'n', 'load_c', 'n', 'R');
INSERT INTO programa VALUES ('load_c', 'o', 'load_c', 'o', 'R');
INSERT INTO programa VALUES ('load_c', 'p', 'load_c', 'p', 'R');
INSERT INTO programa VALUES ('load_c', 'q', 'load_c', 'q', 'R');
INSERT INTO programa VALUES ('load_c', 'r', 'load_c', 'r', 'R');
INSERT INTO programa VALUES ('load_c', 's', 'load_c', 's', 'R');
INSERT INTO programa VALUES ('load_c', 't', 'load_c', 't', 'R');
INSERT INTO programa VALUES ('load_c', 'u', 'load_c', 'u', 'R');
INSERT INTO programa VALUES ('load_c', 'v', 'load_c', 'v', 'R');
INSERT INTO programa VALUES ('load_c', 'w', 'load_c', 'w', 'R');
INSERT INTO programa VALUES ('load_c', 'x', 'load_c', 'x', 'R');
INSERT INTO programa VALUES ('load_c', 'y', 'load_c', 'y', 'R');
INSERT INTO programa VALUES ('load_c', 'z', 'load_c', 'z', 'R');
INSERT INTO programa VALUES ('load_c', 'X', 'load_c', 'X', 'R');
INSERT INTO programa VALUES ('load_c', 'B', 'search_X', 'c', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_d', 'a', 'load_d', 'a', 'R');
INSERT INTO programa VALUES ('load_d', 'b', 'load_d', 'b', 'R');
INSERT INTO programa VALUES ('load_d', 'c', 'load_d', 'c', 'R');
INSERT INTO programa VALUES ('load_d', 'd', 'load_d', 'd', 'R');
INSERT INTO programa VALUES ('load_d', 'e', 'load_d', 'e', 'R');
INSERT INTO programa VALUES ('load_d', 'f', 'load_d', 'f', 'R');
INSERT INTO programa VALUES ('load_d', 'g', 'load_d', 'g', 'R');
INSERT INTO programa VALUES ('load_d', 'h', 'load_d', 'h', 'R');
INSERT INTO programa VALUES ('load_d', 'i', 'load_d', 'i', 'R');
INSERT INTO programa VALUES ('load_d', 'j', 'load_d', 'j', 'R');
INSERT INTO programa VALUES ('load_d', 'k', 'load_d', 'k', 'R');
INSERT INTO programa VALUES ('load_d', 'l', 'load_d', 'l', 'R');
INSERT INTO programa VALUES ('load_d', 'm', 'load_d', 'm', 'R');
INSERT INTO programa VALUES ('load_d', 'n', 'load_d', 'n', 'R');
INSERT INTO programa VALUES ('load_d', 'o', 'load_d', 'o', 'R');
INSERT INTO programa VALUES ('load_d', 'p', 'load_d', 'p', 'R');
INSERT INTO programa VALUES ('load_d', 'q', 'load_d', 'q', 'R');
INSERT INTO programa VALUES ('load_d', 'r', 'load_d', 'r', 'R');
INSERT INTO programa VALUES ('load_d', 's', 'load_d', 's', 'R');
INSERT INTO programa VALUES ('load_d', 't', 'load_d', 't', 'R');
INSERT INTO programa VALUES ('load_d', 'u', 'load_d', 'u', 'R');
INSERT INTO programa VALUES ('load_d', 'v', 'load_d', 'v', 'R');
INSERT INTO programa VALUES ('load_d', 'w', 'load_d', 'w', 'R');
INSERT INTO programa VALUES ('load_d', 'x', 'load_d', 'x', 'R');
INSERT INTO programa VALUES ('load_d', 'y', 'load_d', 'y', 'R');
INSERT INTO programa VALUES ('load_d', 'z', 'load_d', 'z', 'R');
INSERT INTO programa VALUES ('load_d', 'X', 'load_d', 'X', 'R');
INSERT INTO programa VALUES ('load_d', 'B', 'search_X', 'd', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_e', 'a', 'load_e', 'a', 'R');
INSERT INTO programa VALUES ('load_e', 'b', 'load_e', 'b', 'R');
INSERT INTO programa VALUES ('load_e', 'c', 'load_e', 'c', 'R');
INSERT INTO programa VALUES ('load_e', 'd', 'load_e', 'd', 'R');
INSERT INTO programa VALUES ('load_e', 'e', 'load_e', 'e', 'R');
INSERT INTO programa VALUES ('load_e', 'f', 'load_e', 'f', 'R');
INSERT INTO programa VALUES ('load_e', 'g', 'load_e', 'g', 'R');
INSERT INTO programa VALUES ('load_e', 'h', 'load_e', 'h', 'R');
INSERT INTO programa VALUES ('load_e', 'i', 'load_e', 'i', 'R');
INSERT INTO programa VALUES ('load_e', 'j', 'load_e', 'j', 'R');
INSERT INTO programa VALUES ('load_e', 'k', 'load_e', 'k', 'R');
INSERT INTO programa VALUES ('load_e', 'l', 'load_e', 'l', 'R');
INSERT INTO programa VALUES ('load_e', 'm', 'load_e', 'm', 'R');
INSERT INTO programa VALUES ('load_e', 'n', 'load_e', 'n', 'R');
INSERT INTO programa VALUES ('load_e', 'o', 'load_e', 'o', 'R');
INSERT INTO programa VALUES ('load_e', 'p', 'load_e', 'p', 'R');
INSERT INTO programa VALUES ('load_e', 'q', 'load_e', 'q', 'R');
INSERT INTO programa VALUES ('load_e', 'r', 'load_e', 'r', 'R');
INSERT INTO programa VALUES ('load_e', 's', 'load_e', 's', 'R');
INSERT INTO programa VALUES ('load_e', 't', 'load_e', 't', 'R');
INSERT INTO programa VALUES ('load_e', 'u', 'load_e', 'u', 'R');
INSERT INTO programa VALUES ('load_e', 'v', 'load_e', 'v', 'R');
INSERT INTO programa VALUES ('load_e', 'w', 'load_e', 'w', 'R');
INSERT INTO programa VALUES ('load_e', 'x', 'load_e', 'x', 'R');
INSERT INTO programa VALUES ('load_e', 'y', 'load_e', 'y', 'R');
INSERT INTO programa VALUES ('load_e', 'z', 'load_e', 'z', 'R');
INSERT INTO programa VALUES ('load_e', 'X', 'load_e', 'X', 'R');
INSERT INTO programa VALUES ('load_e', 'B', 'search_X', 'e', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_f', 'a', 'load_f', 'a', 'R');
INSERT INTO programa VALUES ('load_f', 'b', 'load_f', 'b', 'R');
INSERT INTO programa VALUES ('load_f', 'c', 'load_f', 'c', 'R');
INSERT INTO programa VALUES ('load_f', 'd', 'load_f', 'd', 'R');
INSERT INTO programa VALUES ('load_f', 'e', 'load_f', 'e', 'R');
INSERT INTO programa VALUES ('load_f', 'f', 'load_f', 'f', 'R');
INSERT INTO programa VALUES ('load_f', 'g', 'load_f', 'g', 'R');
INSERT INTO programa VALUES ('load_f', 'h', 'load_f', 'h', 'R');
INSERT INTO programa VALUES ('load_f', 'i', 'load_f', 'i', 'R');
INSERT INTO programa VALUES ('load_f', 'j', 'load_f', 'j', 'R');
INSERT INTO programa VALUES ('load_f', 'k', 'load_f', 'k', 'R');
INSERT INTO programa VALUES ('load_f', 'l', 'load_f', 'l', 'R');
INSERT INTO programa VALUES ('load_f', 'm', 'load_f', 'm', 'R');
INSERT INTO programa VALUES ('load_f', 'n', 'load_f', 'n', 'R');
INSERT INTO programa VALUES ('load_f', 'o', 'load_f', 'o', 'R');
INSERT INTO programa VALUES ('load_f', 'p', 'load_f', 'p', 'R');
INSERT INTO programa VALUES ('load_f', 'q', 'load_f', 'q', 'R');
INSERT INTO programa VALUES ('load_f', 'r', 'load_f', 'r', 'R');
INSERT INTO programa VALUES ('load_f', 's', 'load_f', 's', 'R');
INSERT INTO programa VALUES ('load_f', 't', 'load_f', 't', 'R');
INSERT INTO programa VALUES ('load_f', 'u', 'load_f', 'u', 'R');
INSERT INTO programa VALUES ('load_f', 'v', 'load_f', 'v', 'R');
INSERT INTO programa VALUES ('load_f', 'w', 'load_f', 'w', 'R');
INSERT INTO programa VALUES ('load_f', 'x', 'load_f', 'x', 'R');
INSERT INTO programa VALUES ('load_f', 'y', 'load_f', 'y', 'R');
INSERT INTO programa VALUES ('load_f', 'z', 'load_f', 'z', 'R');
INSERT INTO programa VALUES ('load_f', 'X', 'load_f', 'X', 'R');
INSERT INTO programa VALUES ('load_f', 'B', 'search_X', 'f', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_g', 'a', 'load_g', 'a', 'R');
INSERT INTO programa VALUES ('load_g', 'b', 'load_g', 'b', 'R');
INSERT INTO programa VALUES ('load_g', 'c', 'load_g', 'c', 'R');
INSERT INTO programa VALUES ('load_g', 'd', 'load_g', 'd', 'R');
INSERT INTO programa VALUES ('load_g', 'e', 'load_g', 'e', 'R');
INSERT INTO programa VALUES ('load_g', 'f', 'load_g', 'f', 'R');
INSERT INTO programa VALUES ('load_g', 'g', 'load_g', 'g', 'R');
INSERT INTO programa VALUES ('load_g', 'h', 'load_g', 'h', 'R');
INSERT INTO programa VALUES ('load_g', 'i', 'load_g', 'i', 'R');
INSERT INTO programa VALUES ('load_g', 'j', 'load_g', 'j', 'R');
INSERT INTO programa VALUES ('load_g', 'k', 'load_g', 'k', 'R');
INSERT INTO programa VALUES ('load_g', 'l', 'load_g', 'l', 'R');
INSERT INTO programa VALUES ('load_g', 'm', 'load_g', 'm', 'R');
INSERT INTO programa VALUES ('load_g', 'n', 'load_g', 'n', 'R');
INSERT INTO programa VALUES ('load_g', 'o', 'load_g', 'o', 'R');
INSERT INTO programa VALUES ('load_g', 'p', 'load_g', 'p', 'R');
INSERT INTO programa VALUES ('load_g', 'q', 'load_g', 'q', 'R');
INSERT INTO programa VALUES ('load_g', 'r', 'load_g', 'r', 'R');
INSERT INTO programa VALUES ('load_g', 's', 'load_g', 's', 'R');
INSERT INTO programa VALUES ('load_g', 't', 'load_g', 't', 'R');
INSERT INTO programa VALUES ('load_g', 'u', 'load_g', 'u', 'R');
INSERT INTO programa VALUES ('load_g', 'v', 'load_g', 'v', 'R');
INSERT INTO programa VALUES ('load_g', 'w', 'load_g', 'w', 'R');
INSERT INTO programa VALUES ('load_g', 'x', 'load_g', 'x', 'R');
INSERT INTO programa VALUES ('load_g', 'y', 'load_g', 'y', 'R');
INSERT INTO programa VALUES ('load_g', 'z', 'load_g', 'z', 'R');
INSERT INTO programa VALUES ('load_g', 'X', 'load_g', 'X', 'R');
INSERT INTO programa VALUES ('load_g', 'B', 'search_X', 'g', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_h', 'a', 'load_h', 'a', 'R');
INSERT INTO programa VALUES ('load_h', 'b', 'load_h', 'b', 'R');
INSERT INTO programa VALUES ('load_h', 'c', 'load_h', 'c', 'R');
INSERT INTO programa VALUES ('load_h', 'd', 'load_h', 'd', 'R');
INSERT INTO programa VALUES ('load_h', 'e', 'load_h', 'e', 'R');
INSERT INTO programa VALUES ('load_h', 'f', 'load_h', 'f', 'R');
INSERT INTO programa VALUES ('load_h', 'g', 'load_h', 'g', 'R');
INSERT INTO programa VALUES ('load_h', 'h', 'load_h', 'h', 'R');
INSERT INTO programa VALUES ('load_h', 'i', 'load_h', 'i', 'R');
INSERT INTO programa VALUES ('load_h', 'j', 'load_h', 'j', 'R');
INSERT INTO programa VALUES ('load_h', 'k', 'load_h', 'k', 'R');
INSERT INTO programa VALUES ('load_h', 'l', 'load_h', 'l', 'R');
INSERT INTO programa VALUES ('load_h', 'm', 'load_h', 'm', 'R');
INSERT INTO programa VALUES ('load_h', 'n', 'load_h', 'n', 'R');
INSERT INTO programa VALUES ('load_h', 'o', 'load_h', 'o', 'R');
INSERT INTO programa VALUES ('load_h', 'p', 'load_h', 'p', 'R');
INSERT INTO programa VALUES ('load_h', 'q', 'load_h', 'q', 'R');
INSERT INTO programa VALUES ('load_h', 'r', 'load_h', 'r', 'R');
INSERT INTO programa VALUES ('load_h', 's', 'load_h', 's', 'R');
INSERT INTO programa VALUES ('load_h', 't', 'load_h', 't', 'R');
INSERT INTO programa VALUES ('load_h', 'u', 'load_h', 'u', 'R');
INSERT INTO programa VALUES ('load_h', 'v', 'load_h', 'v', 'R');
INSERT INTO programa VALUES ('load_h', 'w', 'load_h', 'w', 'R');
INSERT INTO programa VALUES ('load_h', 'x', 'load_h', 'x', 'R');
INSERT INTO programa VALUES ('load_h', 'y', 'load_h', 'y', 'R');
INSERT INTO programa VALUES ('load_h', 'z', 'load_h', 'z', 'R');
INSERT INTO programa VALUES ('load_h', 'X', 'load_h', 'X', 'R');
INSERT INTO programa VALUES ('load_h', 'B', 'search_X', 'h', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_i', 'a', 'load_i', 'a', 'R');
INSERT INTO programa VALUES ('load_i', 'b', 'load_i', 'b', 'R');
INSERT INTO programa VALUES ('load_i', 'c', 'load_i', 'c', 'R');
INSERT INTO programa VALUES ('load_i', 'd', 'load_i', 'd', 'R');
INSERT INTO programa VALUES ('load_i', 'e', 'load_i', 'e', 'R');
INSERT INTO programa VALUES ('load_i', 'f', 'load_i', 'f', 'R');
INSERT INTO programa VALUES ('load_i', 'g', 'load_i', 'g', 'R');
INSERT INTO programa VALUES ('load_i', 'h', 'load_i', 'h', 'R');
INSERT INTO programa VALUES ('load_i', 'i', 'load_i', 'i', 'R');
INSERT INTO programa VALUES ('load_i', 'j', 'load_i', 'j', 'R');
INSERT INTO programa VALUES ('load_i', 'k', 'load_i', 'k', 'R');
INSERT INTO programa VALUES ('load_i', 'l', 'load_i', 'l', 'R');
INSERT INTO programa VALUES ('load_i', 'm', 'load_i', 'm', 'R');
INSERT INTO programa VALUES ('load_i', 'n', 'load_i', 'n', 'R');
INSERT INTO programa VALUES ('load_i', 'o', 'load_i', 'o', 'R');
INSERT INTO programa VALUES ('load_i', 'p', 'load_i', 'p', 'R');
INSERT INTO programa VALUES ('load_i', 'q', 'load_i', 'q', 'R');
INSERT INTO programa VALUES ('load_i', 'r', 'load_i', 'r', 'R');
INSERT INTO programa VALUES ('load_i', 's', 'load_i', 's', 'R');
INSERT INTO programa VALUES ('load_i', 't', 'load_i', 't', 'R');
INSERT INTO programa VALUES ('load_i', 'u', 'load_i', 'u', 'R');
INSERT INTO programa VALUES ('load_i', 'v', 'load_i', 'v', 'R');
INSERT INTO programa VALUES ('load_i', 'w', 'load_i', 'w', 'R');
INSERT INTO programa VALUES ('load_i', 'x', 'load_i', 'x', 'R');
INSERT INTO programa VALUES ('load_i', 'y', 'load_i', 'y', 'R');
INSERT INTO programa VALUES ('load_i', 'z', 'load_i', 'z', 'R');
INSERT INTO programa VALUES ('load_i', 'X', 'load_i', 'X', 'R');
INSERT INTO programa VALUES ('load_i', 'B', 'search_X', 'i', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_j', 'a', 'load_j', 'a', 'R');
INSERT INTO programa VALUES ('load_j', 'b', 'load_j', 'b', 'R');
INSERT INTO programa VALUES ('load_j', 'c', 'load_j', 'c', 'R');
INSERT INTO programa VALUES ('load_j', 'd', 'load_j', 'd', 'R');
INSERT INTO programa VALUES ('load_j', 'e', 'load_j', 'e', 'R');
INSERT INTO programa VALUES ('load_j', 'f', 'load_j', 'f', 'R');
INSERT INTO programa VALUES ('load_j', 'g', 'load_j', 'g', 'R');
INSERT INTO programa VALUES ('load_j', 'h', 'load_j', 'h', 'R');
INSERT INTO programa VALUES ('load_j', 'i', 'load_j', 'i', 'R');
INSERT INTO programa VALUES ('load_j', 'j', 'load_j', 'j', 'R');
INSERT INTO programa VALUES ('load_j', 'k', 'load_j', 'k', 'R');
INSERT INTO programa VALUES ('load_j', 'l', 'load_j', 'l', 'R');
INSERT INTO programa VALUES ('load_j', 'm', 'load_j', 'm', 'R');
INSERT INTO programa VALUES ('load_j', 'n', 'load_j', 'n', 'R');
INSERT INTO programa VALUES ('load_j', 'o', 'load_j', 'o', 'R');
INSERT INTO programa VALUES ('load_j', 'p', 'load_j', 'p', 'R');
INSERT INTO programa VALUES ('load_j', 'q', 'load_j', 'q', 'R');
INSERT INTO programa VALUES ('load_j', 'r', 'load_j', 'r', 'R');
INSERT INTO programa VALUES ('load_j', 's', 'load_j', 's', 'R');
INSERT INTO programa VALUES ('load_j', 't', 'load_j', 't', 'R');
INSERT INTO programa VALUES ('load_j', 'u', 'load_j', 'u', 'R');
INSERT INTO programa VALUES ('load_j', 'v', 'load_j', 'v', 'R');
INSERT INTO programa VALUES ('load_j', 'w', 'load_j', 'w', 'R');
INSERT INTO programa VALUES ('load_j', 'x', 'load_j', 'x', 'R');
INSERT INTO programa VALUES ('load_j', 'y', 'load_j', 'y', 'R');
INSERT INTO programa VALUES ('load_j', 'z', 'load_j', 'z', 'R');
INSERT INTO programa VALUES ('load_j', 'X', 'load_j', 'X', 'R');
INSERT INTO programa VALUES ('load_j', 'B', 'search_X', 'j', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_k', 'a', 'load_k', 'a', 'R');
INSERT INTO programa VALUES ('load_k', 'b', 'load_k', 'b', 'R');
INSERT INTO programa VALUES ('load_k', 'c', 'load_k', 'c', 'R');
INSERT INTO programa VALUES ('load_k', 'd', 'load_k', 'd', 'R');
INSERT INTO programa VALUES ('load_k', 'e', 'load_k', 'e', 'R');
INSERT INTO programa VALUES ('load_k', 'f', 'load_k', 'f', 'R');
INSERT INTO programa VALUES ('load_k', 'g', 'load_k', 'g', 'R');
INSERT INTO programa VALUES ('load_k', 'h', 'load_k', 'h', 'R');
INSERT INTO programa VALUES ('load_k', 'i', 'load_k', 'i', 'R');
INSERT INTO programa VALUES ('load_k', 'j', 'load_k', 'j', 'R');
INSERT INTO programa VALUES ('load_k', 'k', 'load_k', 'k', 'R');
INSERT INTO programa VALUES ('load_k', 'l', 'load_k', 'l', 'R');
INSERT INTO programa VALUES ('load_k', 'm', 'load_k', 'm', 'R');
INSERT INTO programa VALUES ('load_k', 'n', 'load_k', 'n', 'R');
INSERT INTO programa VALUES ('load_k', 'o', 'load_k', 'o', 'R');
INSERT INTO programa VALUES ('load_k', 'p', 'load_k', 'p', 'R');
INSERT INTO programa VALUES ('load_k', 'q', 'load_k', 'q', 'R');
INSERT INTO programa VALUES ('load_k', 'r', 'load_k', 'r', 'R');
INSERT INTO programa VALUES ('load_k', 's', 'load_k', 's', 'R');
INSERT INTO programa VALUES ('load_k', 't', 'load_k', 't', 'R');
INSERT INTO programa VALUES ('load_k', 'u', 'load_k', 'u', 'R');
INSERT INTO programa VALUES ('load_k', 'v', 'load_k', 'v', 'R');
INSERT INTO programa VALUES ('load_k', 'w', 'load_k', 'w', 'R');
INSERT INTO programa VALUES ('load_k', 'x', 'load_k', 'x', 'R');
INSERT INTO programa VALUES ('load_k', 'y', 'load_k', 'y', 'R');
INSERT INTO programa VALUES ('load_k', 'z', 'load_k', 'z', 'R');
INSERT INTO programa VALUES ('load_k', 'X', 'load_k', 'X', 'R');
INSERT INTO programa VALUES ('load_k', 'B', 'search_X', 'k', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_l', 'a', 'load_l', 'a', 'R');
INSERT INTO programa VALUES ('load_l', 'b', 'load_l', 'b', 'R');
INSERT INTO programa VALUES ('load_l', 'c', 'load_l', 'c', 'R');
INSERT INTO programa VALUES ('load_l', 'd', 'load_l', 'd', 'R');
INSERT INTO programa VALUES ('load_l', 'e', 'load_l', 'e', 'R');
INSERT INTO programa VALUES ('load_l', 'f', 'load_l', 'f', 'R');
INSERT INTO programa VALUES ('load_l', 'g', 'load_l', 'g', 'R');
INSERT INTO programa VALUES ('load_l', 'h', 'load_l', 'h', 'R');
INSERT INTO programa VALUES ('load_l', 'i', 'load_l', 'i', 'R');
INSERT INTO programa VALUES ('load_l', 'j', 'load_l', 'j', 'R');
INSERT INTO programa VALUES ('load_l', 'k', 'load_l', 'k', 'R');
INSERT INTO programa VALUES ('load_l', 'l', 'load_l', 'l', 'R');
INSERT INTO programa VALUES ('load_l', 'm', 'load_l', 'm', 'R');
INSERT INTO programa VALUES ('load_l', 'n', 'load_l', 'n', 'R');
INSERT INTO programa VALUES ('load_l', 'o', 'load_l', 'o', 'R');
INSERT INTO programa VALUES ('load_l', 'p', 'load_l', 'p', 'R');
INSERT INTO programa VALUES ('load_l', 'q', 'load_l', 'q', 'R');
INSERT INTO programa VALUES ('load_l', 'r', 'load_l', 'r', 'R');
INSERT INTO programa VALUES ('load_l', 's', 'load_l', 's', 'R');
INSERT INTO programa VALUES ('load_l', 't', 'load_l', 't', 'R');
INSERT INTO programa VALUES ('load_l', 'u', 'load_l', 'u', 'R');
INSERT INTO programa VALUES ('load_l', 'v', 'load_l', 'v', 'R');
INSERT INTO programa VALUES ('load_l', 'w', 'load_l', 'w', 'R');
INSERT INTO programa VALUES ('load_l', 'x', 'load_l', 'x', 'R');
INSERT INTO programa VALUES ('load_l', 'y', 'load_l', 'y', 'R');
INSERT INTO programa VALUES ('load_l', 'z', 'load_l', 'z', 'R');
INSERT INTO programa VALUES ('load_l', 'X', 'load_l', 'X', 'R');
INSERT INTO programa VALUES ('load_l', 'B', 'search_X', 'l', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_m', 'a', 'load_m', 'a', 'R');
INSERT INTO programa VALUES ('load_m', 'b', 'load_m', 'b', 'R');
INSERT INTO programa VALUES ('load_m', 'c', 'load_m', 'c', 'R');
INSERT INTO programa VALUES ('load_m', 'd', 'load_m', 'd', 'R');
INSERT INTO programa VALUES ('load_m', 'e', 'load_m', 'e', 'R');
INSERT INTO programa VALUES ('load_m', 'f', 'load_m', 'f', 'R');
INSERT INTO programa VALUES ('load_m', 'g', 'load_m', 'g', 'R');
INSERT INTO programa VALUES ('load_m', 'h', 'load_m', 'h', 'R');
INSERT INTO programa VALUES ('load_m', 'i', 'load_m', 'i', 'R');
INSERT INTO programa VALUES ('load_m', 'j', 'load_m', 'j', 'R');
INSERT INTO programa VALUES ('load_m', 'k', 'load_m', 'k', 'R');
INSERT INTO programa VALUES ('load_m', 'l', 'load_m', 'l', 'R');
INSERT INTO programa VALUES ('load_m', 'm', 'load_m', 'm', 'R');
INSERT INTO programa VALUES ('load_m', 'n', 'load_m', 'n', 'R');
INSERT INTO programa VALUES ('load_m', 'o', 'load_m', 'o', 'R');
INSERT INTO programa VALUES ('load_m', 'p', 'load_m', 'p', 'R');
INSERT INTO programa VALUES ('load_m', 'q', 'load_m', 'q', 'R');
INSERT INTO programa VALUES ('load_m', 'r', 'load_m', 'r', 'R');
INSERT INTO programa VALUES ('load_m', 's', 'load_m', 's', 'R');
INSERT INTO programa VALUES ('load_m', 't', 'load_m', 't', 'R');
INSERT INTO programa VALUES ('load_m', 'u', 'load_m', 'u', 'R');
INSERT INTO programa VALUES ('load_m', 'v', 'load_m', 'v', 'R');
INSERT INTO programa VALUES ('load_m', 'w', 'load_m', 'w', 'R');
INSERT INTO programa VALUES ('load_m', 'x', 'load_m', 'x', 'R');
INSERT INTO programa VALUES ('load_m', 'y', 'load_m', 'y', 'R');
INSERT INTO programa VALUES ('load_m', 'z', 'load_m', 'z', 'R');
INSERT INTO programa VALUES ('load_m', 'X', 'load_m', 'X', 'R');
INSERT INTO programa VALUES ('load_m', 'B', 'search_X', 'm', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_n', 'a', 'load_n', 'a', 'R');
INSERT INTO programa VALUES ('load_n', 'b', 'load_n', 'b', 'R');
INSERT INTO programa VALUES ('load_n', 'c', 'load_n', 'c', 'R');
INSERT INTO programa VALUES ('load_n', 'd', 'load_n', 'd', 'R');
INSERT INTO programa VALUES ('load_n', 'e', 'load_n', 'e', 'R');
INSERT INTO programa VALUES ('load_n', 'f', 'load_n', 'f', 'R');
INSERT INTO programa VALUES ('load_n', 'g', 'load_n', 'g', 'R');
INSERT INTO programa VALUES ('load_n', 'h', 'load_n', 'h', 'R');
INSERT INTO programa VALUES ('load_n', 'i', 'load_n', 'i', 'R');
INSERT INTO programa VALUES ('load_n', 'j', 'load_n', 'j', 'R');
INSERT INTO programa VALUES ('load_n', 'k', 'load_n', 'k', 'R');
INSERT INTO programa VALUES ('load_n', 'l', 'load_n', 'l', 'R');
INSERT INTO programa VALUES ('load_n', 'm', 'load_n', 'm', 'R');
INSERT INTO programa VALUES ('load_n', 'n', 'load_n', 'n', 'R');
INSERT INTO programa VALUES ('load_n', 'o', 'load_n', 'o', 'R');
INSERT INTO programa VALUES ('load_n', 'p', 'load_n', 'p', 'R');
INSERT INTO programa VALUES ('load_n', 'q', 'load_n', 'q', 'R');
INSERT INTO programa VALUES ('load_n', 'r', 'load_n', 'r', 'R');
INSERT INTO programa VALUES ('load_n', 's', 'load_n', 's', 'R');
INSERT INTO programa VALUES ('load_n', 't', 'load_n', 't', 'R');
INSERT INTO programa VALUES ('load_n', 'u', 'load_n', 'u', 'R');
INSERT INTO programa VALUES ('load_n', 'v', 'load_n', 'v', 'R');
INSERT INTO programa VALUES ('load_n', 'w', 'load_n', 'w', 'R');
INSERT INTO programa VALUES ('load_n', 'x', 'load_n', 'x', 'R');
INSERT INTO programa VALUES ('load_n', 'y', 'load_n', 'y', 'R');
INSERT INTO programa VALUES ('load_n', 'z', 'load_n', 'z', 'R');
INSERT INTO programa VALUES ('load_n', 'X', 'load_n', 'X', 'R');
INSERT INTO programa VALUES ('load_n', 'B', 'search_X', 'n', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_o', 'a', 'load_o', 'a', 'R');
INSERT INTO programa VALUES ('load_o', 'b', 'load_o', 'b', 'R');
INSERT INTO programa VALUES ('load_o', 'c', 'load_o', 'c', 'R');
INSERT INTO programa VALUES ('load_o', 'd', 'load_o', 'd', 'R');
INSERT INTO programa VALUES ('load_o', 'e', 'load_o', 'e', 'R');
INSERT INTO programa VALUES ('load_o', 'f', 'load_o', 'f', 'R');
INSERT INTO programa VALUES ('load_o', 'g', 'load_o', 'g', 'R');
INSERT INTO programa VALUES ('load_o', 'h', 'load_o', 'h', 'R');
INSERT INTO programa VALUES ('load_o', 'i', 'load_o', 'i', 'R');
INSERT INTO programa VALUES ('load_o', 'j', 'load_o', 'j', 'R');
INSERT INTO programa VALUES ('load_o', 'k', 'load_o', 'k', 'R');
INSERT INTO programa VALUES ('load_o', 'l', 'load_o', 'l', 'R');
INSERT INTO programa VALUES ('load_o', 'm', 'load_o', 'm', 'R');
INSERT INTO programa VALUES ('load_o', 'n', 'load_o', 'n', 'R');
INSERT INTO programa VALUES ('load_o', 'o', 'load_o', 'o', 'R');
INSERT INTO programa VALUES ('load_o', 'p', 'load_o', 'p', 'R');
INSERT INTO programa VALUES ('load_o', 'q', 'load_o', 'q', 'R');
INSERT INTO programa VALUES ('load_o', 'r', 'load_o', 'r', 'R');
INSERT INTO programa VALUES ('load_o', 's', 'load_o', 's', 'R');
INSERT INTO programa VALUES ('load_o', 't', 'load_o', 't', 'R');
INSERT INTO programa VALUES ('load_o', 'u', 'load_o', 'u', 'R');
INSERT INTO programa VALUES ('load_o', 'v', 'load_o', 'v', 'R');
INSERT INTO programa VALUES ('load_o', 'w', 'load_o', 'w', 'R');
INSERT INTO programa VALUES ('load_o', 'x', 'load_o', 'x', 'R');
INSERT INTO programa VALUES ('load_o', 'y', 'load_o', 'y', 'R');
INSERT INTO programa VALUES ('load_o', 'z', 'load_o', 'z', 'R');
INSERT INTO programa VALUES ('load_o', 'X', 'load_o', 'X', 'R');
INSERT INTO programa VALUES ('load_o', 'B', 'search_X', 'o', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_p', 'a', 'load_p', 'a', 'R');
INSERT INTO programa VALUES ('load_p', 'b', 'load_p', 'b', 'R');
INSERT INTO programa VALUES ('load_p', 'c', 'load_p', 'c', 'R');
INSERT INTO programa VALUES ('load_p', 'd', 'load_p', 'd', 'R');
INSERT INTO programa VALUES ('load_p', 'e', 'load_p', 'e', 'R');
INSERT INTO programa VALUES ('load_p', 'f', 'load_p', 'f', 'R');
INSERT INTO programa VALUES ('load_p', 'g', 'load_p', 'g', 'R');
INSERT INTO programa VALUES ('load_p', 'h', 'load_p', 'h', 'R');
INSERT INTO programa VALUES ('load_p', 'i', 'load_p', 'i', 'R');
INSERT INTO programa VALUES ('load_p', 'j', 'load_p', 'j', 'R');
INSERT INTO programa VALUES ('load_p', 'k', 'load_p', 'k', 'R');
INSERT INTO programa VALUES ('load_p', 'l', 'load_p', 'l', 'R');
INSERT INTO programa VALUES ('load_p', 'm', 'load_p', 'm', 'R');
INSERT INTO programa VALUES ('load_p', 'n', 'load_p', 'n', 'R');
INSERT INTO programa VALUES ('load_p', 'o', 'load_p', 'o', 'R');
INSERT INTO programa VALUES ('load_p', 'p', 'load_p', 'p', 'R');
INSERT INTO programa VALUES ('load_p', 'q', 'load_p', 'q', 'R');
INSERT INTO programa VALUES ('load_p', 'r', 'load_p', 'r', 'R');
INSERT INTO programa VALUES ('load_p', 's', 'load_p', 's', 'R');
INSERT INTO programa VALUES ('load_p', 't', 'load_p', 't', 'R');
INSERT INTO programa VALUES ('load_p', 'u', 'load_p', 'u', 'R');
INSERT INTO programa VALUES ('load_p', 'v', 'load_p', 'v', 'R');
INSERT INTO programa VALUES ('load_p', 'w', 'load_p', 'w', 'R');
INSERT INTO programa VALUES ('load_p', 'x', 'load_p', 'x', 'R');
INSERT INTO programa VALUES ('load_p', 'y', 'load_p', 'y', 'R');
INSERT INTO programa VALUES ('load_p', 'z', 'load_p', 'z', 'R');
INSERT INTO programa VALUES ('load_p', 'X', 'load_p', 'X', 'R');
INSERT INTO programa VALUES ('load_p', 'B', 'search_X', 'p', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_q', 'a', 'load_q', 'a', 'R');
INSERT INTO programa VALUES ('load_q', 'b', 'load_q', 'b', 'R');
INSERT INTO programa VALUES ('load_q', 'c', 'load_q', 'c', 'R');
INSERT INTO programa VALUES ('load_q', 'd', 'load_q', 'd', 'R');
INSERT INTO programa VALUES ('load_q', 'e', 'load_q', 'e', 'R');
INSERT INTO programa VALUES ('load_q', 'f', 'load_q', 'f', 'R');
INSERT INTO programa VALUES ('load_q', 'g', 'load_q', 'g', 'R');
INSERT INTO programa VALUES ('load_q', 'h', 'load_q', 'h', 'R');
INSERT INTO programa VALUES ('load_q', 'i', 'load_q', 'i', 'R');
INSERT INTO programa VALUES ('load_q', 'j', 'load_q', 'j', 'R');
INSERT INTO programa VALUES ('load_q', 'k', 'load_q', 'k', 'R');
INSERT INTO programa VALUES ('load_q', 'l', 'load_q', 'l', 'R');
INSERT INTO programa VALUES ('load_q', 'm', 'load_q', 'm', 'R');
INSERT INTO programa VALUES ('load_q', 'n', 'load_q', 'n', 'R');
INSERT INTO programa VALUES ('load_q', 'o', 'load_q', 'o', 'R');
INSERT INTO programa VALUES ('load_q', 'p', 'load_q', 'p', 'R');
INSERT INTO programa VALUES ('load_q', 'q', 'load_q', 'q', 'R');
INSERT INTO programa VALUES ('load_q', 'r', 'load_q', 'r', 'R');
INSERT INTO programa VALUES ('load_q', 's', 'load_q', 's', 'R');
INSERT INTO programa VALUES ('load_q', 't', 'load_q', 't', 'R');
INSERT INTO programa VALUES ('load_q', 'u', 'load_q', 'u', 'R');
INSERT INTO programa VALUES ('load_q', 'v', 'load_q', 'v', 'R');
INSERT INTO programa VALUES ('load_q', 'w', 'load_q', 'w', 'R');
INSERT INTO programa VALUES ('load_q', 'x', 'load_q', 'x', 'R');
INSERT INTO programa VALUES ('load_q', 'y', 'load_q', 'y', 'R');
INSERT INTO programa VALUES ('load_q', 'z', 'load_q', 'z', 'R');
INSERT INTO programa VALUES ('load_q', 'X', 'load_q', 'X', 'R');
INSERT INTO programa VALUES ('load_q', 'B', 'search_X', 'q', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_r', 'a', 'load_r', 'a', 'R');
INSERT INTO programa VALUES ('load_r', 'b', 'load_r', 'b', 'R');
INSERT INTO programa VALUES ('load_r', 'c', 'load_r', 'c', 'R');
INSERT INTO programa VALUES ('load_r', 'd', 'load_r', 'd', 'R');
INSERT INTO programa VALUES ('load_r', 'e', 'load_r', 'e', 'R');
INSERT INTO programa VALUES ('load_r', 'f', 'load_r', 'f', 'R');
INSERT INTO programa VALUES ('load_r', 'g', 'load_r', 'g', 'R');
INSERT INTO programa VALUES ('load_r', 'h', 'load_r', 'h', 'R');
INSERT INTO programa VALUES ('load_r', 'i', 'load_r', 'i', 'R');
INSERT INTO programa VALUES ('load_r', 'j', 'load_r', 'j', 'R');
INSERT INTO programa VALUES ('load_r', 'k', 'load_r', 'k', 'R');
INSERT INTO programa VALUES ('load_r', 'l', 'load_r', 'l', 'R');
INSERT INTO programa VALUES ('load_r', 'm', 'load_r', 'm', 'R');
INSERT INTO programa VALUES ('load_r', 'n', 'load_r', 'n', 'R');
INSERT INTO programa VALUES ('load_r', 'o', 'load_r', 'o', 'R');
INSERT INTO programa VALUES ('load_r', 'p', 'load_r', 'p', 'R');
INSERT INTO programa VALUES ('load_r', 'q', 'load_r', 'q', 'R');
INSERT INTO programa VALUES ('load_r', 'r', 'load_r', 'r', 'R');
INSERT INTO programa VALUES ('load_r', 's', 'load_r', 's', 'R');
INSERT INTO programa VALUES ('load_r', 't', 'load_r', 't', 'R');
INSERT INTO programa VALUES ('load_r', 'u', 'load_r', 'u', 'R');
INSERT INTO programa VALUES ('load_r', 'v', 'load_r', 'v', 'R');
INSERT INTO programa VALUES ('load_r', 'w', 'load_r', 'w', 'R');
INSERT INTO programa VALUES ('load_r', 'x', 'load_r', 'x', 'R');
INSERT INTO programa VALUES ('load_r', 'y', 'load_r', 'y', 'R');
INSERT INTO programa VALUES ('load_r', 'z', 'load_r', 'z', 'R');
INSERT INTO programa VALUES ('load_r', 'X', 'load_r', 'X', 'R');
INSERT INTO programa VALUES ('load_r', 'B', 'search_X', 'r', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_s', 'a', 'load_s', 'a', 'R');
INSERT INTO programa VALUES ('load_s', 'b', 'load_s', 'b', 'R');
INSERT INTO programa VALUES ('load_s', 'c', 'load_s', 'c', 'R');
INSERT INTO programa VALUES ('load_s', 'd', 'load_s', 'd', 'R');
INSERT INTO programa VALUES ('load_s', 'e', 'load_s', 'e', 'R');
INSERT INTO programa VALUES ('load_s', 'f', 'load_s', 'f', 'R');
INSERT INTO programa VALUES ('load_s', 'g', 'load_s', 'g', 'R');
INSERT INTO programa VALUES ('load_s', 'h', 'load_s', 'h', 'R');
INSERT INTO programa VALUES ('load_s', 'i', 'load_s', 'i', 'R');
INSERT INTO programa VALUES ('load_s', 'j', 'load_s', 'j', 'R');
INSERT INTO programa VALUES ('load_s', 'k', 'load_s', 'k', 'R');
INSERT INTO programa VALUES ('load_s', 'l', 'load_s', 'l', 'R');
INSERT INTO programa VALUES ('load_s', 'm', 'load_s', 'm', 'R');
INSERT INTO programa VALUES ('load_s', 'n', 'load_s', 'n', 'R');
INSERT INTO programa VALUES ('load_s', 'o', 'load_s', 'o', 'R');
INSERT INTO programa VALUES ('load_s', 'p', 'load_s', 'p', 'R');
INSERT INTO programa VALUES ('load_s', 'q', 'load_s', 'q', 'R');
INSERT INTO programa VALUES ('load_s', 'r', 'load_s', 'r', 'R');
INSERT INTO programa VALUES ('load_s', 's', 'load_s', 's', 'R');
INSERT INTO programa VALUES ('load_s', 't', 'load_s', 't', 'R');
INSERT INTO programa VALUES ('load_s', 'u', 'load_s', 'u', 'R');
INSERT INTO programa VALUES ('load_s', 'v', 'load_s', 'v', 'R');
INSERT INTO programa VALUES ('load_s', 'w', 'load_s', 'w', 'R');
INSERT INTO programa VALUES ('load_s', 'x', 'load_s', 'x', 'R');
INSERT INTO programa VALUES ('load_s', 'y', 'load_s', 'y', 'R');
INSERT INTO programa VALUES ('load_s', 'z', 'load_s', 'z', 'R');
INSERT INTO programa VALUES ('load_s', 'X', 'load_s', 'X', 'R');
INSERT INTO programa VALUES ('load_s', 'B', 'search_X', 's', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_t', 'a', 'load_t', 'a', 'R');
INSERT INTO programa VALUES ('load_t', 'b', 'load_t', 'b', 'R');
INSERT INTO programa VALUES ('load_t', 'c', 'load_t', 'c', 'R');
INSERT INTO programa VALUES ('load_t', 'd', 'load_t', 'd', 'R');
INSERT INTO programa VALUES ('load_t', 'e', 'load_t', 'e', 'R');
INSERT INTO programa VALUES ('load_t', 'f', 'load_t', 'f', 'R');
INSERT INTO programa VALUES ('load_t', 'g', 'load_t', 'g', 'R');
INSERT INTO programa VALUES ('load_t', 'h', 'load_t', 'h', 'R');
INSERT INTO programa VALUES ('load_t', 'i', 'load_t', 'i', 'R');
INSERT INTO programa VALUES ('load_t', 'j', 'load_t', 'j', 'R');
INSERT INTO programa VALUES ('load_t', 'k', 'load_t', 'k', 'R');
INSERT INTO programa VALUES ('load_t', 'l', 'load_t', 'l', 'R');
INSERT INTO programa VALUES ('load_t', 'm', 'load_t', 'm', 'R');
INSERT INTO programa VALUES ('load_t', 'n', 'load_t', 'n', 'R');
INSERT INTO programa VALUES ('load_t', 'o', 'load_t', 'o', 'R');
INSERT INTO programa VALUES ('load_t', 'p', 'load_t', 'p', 'R');
INSERT INTO programa VALUES ('load_t', 'q', 'load_t', 'q', 'R');
INSERT INTO programa VALUES ('load_t', 'r', 'load_t', 'r', 'R');
INSERT INTO programa VALUES ('load_t', 's', 'load_t', 's', 'R');
INSERT INTO programa VALUES ('load_t', 't', 'load_t', 't', 'R');
INSERT INTO programa VALUES ('load_t', 'u', 'load_t', 'u', 'R');
INSERT INTO programa VALUES ('load_t', 'v', 'load_t', 'v', 'R');
INSERT INTO programa VALUES ('load_t', 'w', 'load_t', 'w', 'R');
INSERT INTO programa VALUES ('load_t', 'x', 'load_t', 'x', 'R');
INSERT INTO programa VALUES ('load_t', 'y', 'load_t', 'y', 'R');
INSERT INTO programa VALUES ('load_t', 'z', 'load_t', 'z', 'R');
INSERT INTO programa VALUES ('load_t', 'X', 'load_t', 'X', 'R');
INSERT INTO programa VALUES ('load_t', 'B', 'search_X', 't', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_u', 'a', 'load_u', 'a', 'R');
INSERT INTO programa VALUES ('load_u', 'b', 'load_u', 'b', 'R');
INSERT INTO programa VALUES ('load_u', 'c', 'load_u', 'c', 'R');
INSERT INTO programa VALUES ('load_u', 'd', 'load_u', 'd', 'R');
INSERT INTO programa VALUES ('load_u', 'e', 'load_u', 'e', 'R');
INSERT INTO programa VALUES ('load_u', 'f', 'load_u', 'f', 'R');
INSERT INTO programa VALUES ('load_u', 'g', 'load_u', 'g', 'R');
INSERT INTO programa VALUES ('load_u', 'h', 'load_u', 'h', 'R');
INSERT INTO programa VALUES ('load_u', 'i', 'load_u', 'i', 'R');
INSERT INTO programa VALUES ('load_u', 'j', 'load_u', 'j', 'R');
INSERT INTO programa VALUES ('load_u', 'k', 'load_u', 'k', 'R');
INSERT INTO programa VALUES ('load_u', 'l', 'load_u', 'l', 'R');
INSERT INTO programa VALUES ('load_u', 'm', 'load_u', 'm', 'R');
INSERT INTO programa VALUES ('load_u', 'n', 'load_u', 'n', 'R');
INSERT INTO programa VALUES ('load_u', 'o', 'load_u', 'o', 'R');
INSERT INTO programa VALUES ('load_u', 'p', 'load_u', 'p', 'R');
INSERT INTO programa VALUES ('load_u', 'q', 'load_u', 'q', 'R');
INSERT INTO programa VALUES ('load_u', 'r', 'load_u', 'r', 'R');
INSERT INTO programa VALUES ('load_u', 's', 'load_u', 's', 'R');
INSERT INTO programa VALUES ('load_u', 't', 'load_u', 't', 'R');
INSERT INTO programa VALUES ('load_u', 'u', 'load_u', 'u', 'R');
INSERT INTO programa VALUES ('load_u', 'v', 'load_u', 'v', 'R');
INSERT INTO programa VALUES ('load_u', 'w', 'load_u', 'w', 'R');
INSERT INTO programa VALUES ('load_u', 'x', 'load_u', 'x', 'R');
INSERT INTO programa VALUES ('load_u', 'y', 'load_u', 'y', 'R');
INSERT INTO programa VALUES ('load_u', 'z', 'load_u', 'z', 'R');
INSERT INTO programa VALUES ('load_u', 'X', 'load_u', 'X', 'R');
INSERT INTO programa VALUES ('load_u', 'B', 'search_X', 'u', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_v', 'a', 'load_v', 'a', 'R');
INSERT INTO programa VALUES ('load_v', 'b', 'load_v', 'b', 'R');
INSERT INTO programa VALUES ('load_v', 'c', 'load_v', 'c', 'R');
INSERT INTO programa VALUES ('load_v', 'd', 'load_v', 'd', 'R');
INSERT INTO programa VALUES ('load_v', 'e', 'load_v', 'e', 'R');
INSERT INTO programa VALUES ('load_v', 'f', 'load_v', 'f', 'R');
INSERT INTO programa VALUES ('load_v', 'g', 'load_v', 'g', 'R');
INSERT INTO programa VALUES ('load_v', 'h', 'load_v', 'h', 'R');
INSERT INTO programa VALUES ('load_v', 'i', 'load_v', 'i', 'R');
INSERT INTO programa VALUES ('load_v', 'j', 'load_v', 'j', 'R');
INSERT INTO programa VALUES ('load_v', 'k', 'load_v', 'k', 'R');
INSERT INTO programa VALUES ('load_v', 'l', 'load_v', 'l', 'R');
INSERT INTO programa VALUES ('load_v', 'm', 'load_v', 'm', 'R');
INSERT INTO programa VALUES ('load_v', 'n', 'load_v', 'n', 'R');
INSERT INTO programa VALUES ('load_v', 'o', 'load_v', 'o', 'R');
INSERT INTO programa VALUES ('load_v', 'p', 'load_v', 'p', 'R');
INSERT INTO programa VALUES ('load_v', 'q', 'load_v', 'q', 'R');
INSERT INTO programa VALUES ('load_v', 'r', 'load_v', 'r', 'R');
INSERT INTO programa VALUES ('load_v', 's', 'load_v', 's', 'R');
INSERT INTO programa VALUES ('load_v', 't', 'load_v', 't', 'R');
INSERT INTO programa VALUES ('load_v', 'u', 'load_v', 'u', 'R');
INSERT INTO programa VALUES ('load_v', 'v', 'load_v', 'v', 'R');
INSERT INTO programa VALUES ('load_v', 'w', 'load_v', 'w', 'R');
INSERT INTO programa VALUES ('load_v', 'x', 'load_v', 'x', 'R');
INSERT INTO programa VALUES ('load_v', 'y', 'load_v', 'y', 'R');
INSERT INTO programa VALUES ('load_v', 'z', 'load_v', 'z', 'R');
INSERT INTO programa VALUES ('load_v', 'X', 'load_v', 'X', 'R');
INSERT INTO programa VALUES ('load_v', 'B', 'search_X', 'v', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_w', 'a', 'load_w', 'a', 'R');
INSERT INTO programa VALUES ('load_w', 'b', 'load_w', 'b', 'R');
INSERT INTO programa VALUES ('load_w', 'c', 'load_w', 'c', 'R');
INSERT INTO programa VALUES ('load_w', 'd', 'load_w', 'd', 'R');
INSERT INTO programa VALUES ('load_w', 'e', 'load_w', 'e', 'R');
INSERT INTO programa VALUES ('load_w', 'f', 'load_w', 'f', 'R');
INSERT INTO programa VALUES ('load_w', 'g', 'load_w', 'g', 'R');
INSERT INTO programa VALUES ('load_w', 'h', 'load_w', 'h', 'R');
INSERT INTO programa VALUES ('load_w', 'i', 'load_w', 'i', 'R');
INSERT INTO programa VALUES ('load_w', 'j', 'load_w', 'j', 'R');
INSERT INTO programa VALUES ('load_w', 'k', 'load_w', 'k', 'R');
INSERT INTO programa VALUES ('load_w', 'l', 'load_w', 'l', 'R');
INSERT INTO programa VALUES ('load_w', 'm', 'load_w', 'm', 'R');
INSERT INTO programa VALUES ('load_w', 'n', 'load_w', 'n', 'R');
INSERT INTO programa VALUES ('load_w', 'o', 'load_w', 'o', 'R');
INSERT INTO programa VALUES ('load_w', 'p', 'load_w', 'p', 'R');
INSERT INTO programa VALUES ('load_w', 'q', 'load_w', 'q', 'R');
INSERT INTO programa VALUES ('load_w', 'r', 'load_w', 'r', 'R');
INSERT INTO programa VALUES ('load_w', 's', 'load_w', 's', 'R');
INSERT INTO programa VALUES ('load_w', 't', 'load_w', 't', 'R');
INSERT INTO programa VALUES ('load_w', 'u', 'load_w', 'u', 'R');
INSERT INTO programa VALUES ('load_w', 'v', 'load_w', 'v', 'R');
INSERT INTO programa VALUES ('load_w', 'w', 'load_w', 'w', 'R');
INSERT INTO programa VALUES ('load_w', 'x', 'load_w', 'x', 'R');
INSERT INTO programa VALUES ('load_w', 'y', 'load_w', 'y', 'R');
INSERT INTO programa VALUES ('load_w', 'z', 'load_w', 'z', 'R');
INSERT INTO programa VALUES ('load_w', 'X', 'load_w', 'X', 'R');
INSERT INTO programa VALUES ('load_w', 'B', 'search_X', 'w', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_x', 'a', 'load_x', 'a', 'R');
INSERT INTO programa VALUES ('load_x', 'b', 'load_x', 'b', 'R');
INSERT INTO programa VALUES ('load_x', 'c', 'load_x', 'c', 'R');
INSERT INTO programa VALUES ('load_x', 'd', 'load_x', 'd', 'R');
INSERT INTO programa VALUES ('load_x', 'e', 'load_x', 'e', 'R');
INSERT INTO programa VALUES ('load_x', 'f', 'load_x', 'f', 'R');
INSERT INTO programa VALUES ('load_x', 'g', 'load_x', 'g', 'R');
INSERT INTO programa VALUES ('load_x', 'h', 'load_x', 'h', 'R');
INSERT INTO programa VALUES ('load_x', 'i', 'load_x', 'i', 'R');
INSERT INTO programa VALUES ('load_x', 'j', 'load_x', 'j', 'R');
INSERT INTO programa VALUES ('load_x', 'k', 'load_x', 'k', 'R');
INSERT INTO programa VALUES ('load_x', 'l', 'load_x', 'l', 'R');
INSERT INTO programa VALUES ('load_x', 'm', 'load_x', 'm', 'R');
INSERT INTO programa VALUES ('load_x', 'n', 'load_x', 'n', 'R');
INSERT INTO programa VALUES ('load_x', 'o', 'load_x', 'o', 'R');
INSERT INTO programa VALUES ('load_x', 'p', 'load_x', 'p', 'R');
INSERT INTO programa VALUES ('load_x', 'q', 'load_x', 'q', 'R');
INSERT INTO programa VALUES ('load_x', 'r', 'load_x', 'r', 'R');
INSERT INTO programa VALUES ('load_x', 's', 'load_x', 's', 'R');
INSERT INTO programa VALUES ('load_x', 't', 'load_x', 't', 'R');
INSERT INTO programa VALUES ('load_x', 'u', 'load_x', 'u', 'R');
INSERT INTO programa VALUES ('load_x', 'v', 'load_x', 'v', 'R');
INSERT INTO programa VALUES ('load_x', 'w', 'load_x', 'w', 'R');
INSERT INTO programa VALUES ('load_x', 'x', 'load_x', 'x', 'R');
INSERT INTO programa VALUES ('load_x', 'y', 'load_x', 'y', 'R');
INSERT INTO programa VALUES ('load_x', 'z', 'load_x', 'z', 'R');
INSERT INTO programa VALUES ('load_x', 'X', 'load_x', 'X', 'R');
INSERT INTO programa VALUES ('load_x', 'B', 'search_X', 'x', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_y', 'a', 'load_y', 'a', 'R');
INSERT INTO programa VALUES ('load_y', 'b', 'load_y', 'b', 'R');
INSERT INTO programa VALUES ('load_y', 'c', 'load_y', 'c', 'R');
INSERT INTO programa VALUES ('load_y', 'd', 'load_y', 'd', 'R');
INSERT INTO programa VALUES ('load_y', 'e', 'load_y', 'e', 'R');
INSERT INTO programa VALUES ('load_y', 'f', 'load_y', 'f', 'R');
INSERT INTO programa VALUES ('load_y', 'g', 'load_y', 'g', 'R');
INSERT INTO programa VALUES ('load_y', 'h', 'load_y', 'h', 'R');
INSERT INTO programa VALUES ('load_y', 'i', 'load_y', 'i', 'R');
INSERT INTO programa VALUES ('load_y', 'j', 'load_y', 'j', 'R');
INSERT INTO programa VALUES ('load_y', 'k', 'load_y', 'k', 'R');
INSERT INTO programa VALUES ('load_y', 'l', 'load_y', 'l', 'R');
INSERT INTO programa VALUES ('load_y', 'm', 'load_y', 'm', 'R');
INSERT INTO programa VALUES ('load_y', 'n', 'load_y', 'n', 'R');
INSERT INTO programa VALUES ('load_y', 'o', 'load_y', 'o', 'R');
INSERT INTO programa VALUES ('load_y', 'p', 'load_y', 'p', 'R');
INSERT INTO programa VALUES ('load_y', 'q', 'load_y', 'q', 'R');
INSERT INTO programa VALUES ('load_y', 'r', 'load_y', 'r', 'R');
INSERT INTO programa VALUES ('load_y', 's', 'load_y', 's', 'R');
INSERT INTO programa VALUES ('load_y', 't', 'load_y', 't', 'R');
INSERT INTO programa VALUES ('load_y', 'u', 'load_y', 'u', 'R');
INSERT INTO programa VALUES ('load_y', 'v', 'load_y', 'v', 'R');
INSERT INTO programa VALUES ('load_y', 'w', 'load_y', 'w', 'R');
INSERT INTO programa VALUES ('load_y', 'x', 'load_y', 'x', 'R');
INSERT INTO programa VALUES ('load_y', 'y', 'load_y', 'y', 'R');
INSERT INTO programa VALUES ('load_y', 'z', 'load_y', 'z', 'R');
INSERT INTO programa VALUES ('load_y', 'X', 'load_y', 'X', 'R');
INSERT INTO programa VALUES ('load_y', 'B', 'search_X', 'y', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

INSERT INTO programa VALUES ('load_z', 'a', 'load_z', 'a', 'R');
INSERT INTO programa VALUES ('load_z', 'b', 'load_z', 'b', 'R');
INSERT INTO programa VALUES ('load_z', 'c', 'load_z', 'c', 'R');
INSERT INTO programa VALUES ('load_z', 'd', 'load_z', 'd', 'R');
INSERT INTO programa VALUES ('load_z', 'e', 'load_z', 'e', 'R');
INSERT INTO programa VALUES ('load_z', 'f', 'load_z', 'f', 'R');
INSERT INTO programa VALUES ('load_z', 'g', 'load_z', 'g', 'R');
INSERT INTO programa VALUES ('load_z', 'h', 'load_z', 'h', 'R');
INSERT INTO programa VALUES ('load_z', 'i', 'load_z', 'i', 'R');
INSERT INTO programa VALUES ('load_z', 'j', 'load_z', 'j', 'R');
INSERT INTO programa VALUES ('load_z', 'k', 'load_z', 'k', 'R');
INSERT INTO programa VALUES ('load_z', 'l', 'load_z', 'l', 'R');
INSERT INTO programa VALUES ('load_z', 'm', 'load_z', 'm', 'R');
INSERT INTO programa VALUES ('load_z', 'n', 'load_z', 'n', 'R');
INSERT INTO programa VALUES ('load_z', 'o', 'load_z', 'o', 'R');
INSERT INTO programa VALUES ('load_z', 'p', 'load_z', 'p', 'R');
INSERT INTO programa VALUES ('load_z', 'q', 'load_z', 'q', 'R');
INSERT INTO programa VALUES ('load_z', 'r', 'load_z', 'r', 'R');
INSERT INTO programa VALUES ('load_z', 's', 'load_z', 's', 'R');
INSERT INTO programa VALUES ('load_z', 't', 'load_z', 't', 'R');
INSERT INTO programa VALUES ('load_z', 'u', 'load_z', 'u', 'R');
INSERT INTO programa VALUES ('load_z', 'v', 'load_z', 'v', 'R');
INSERT INTO programa VALUES ('load_z', 'w', 'load_z', 'w', 'R');
INSERT INTO programa VALUES ('load_z', 'x', 'load_z', 'x', 'R');
INSERT INTO programa VALUES ('load_z', 'y', 'load_z', 'y', 'R');
INSERT INTO programa VALUES ('load_z', 'z', 'load_z', 'z', 'R');
INSERT INTO programa VALUES ('load_z', 'X', 'load_z', 'X', 'R');
INSERT INTO programa VALUES ('load_z', 'B', 'search_X', 'z', 'L');  --PEGA EL VALOR Y SE VA PARA LA IZQUIERDA

--BUSCA ALGUNA X (CORRESPONDEN AL STRING ORIGINAL);
INSERT INTO programa VALUES ('search_X', 'a', 'search_X', 'a', 'L');
INSERT INTO programa VALUES ('search_X', 'b', 'search_X', 'b', 'L');
INSERT INTO programa VALUES ('search_X', 'c', 'search_X', 'c', 'L');
INSERT INTO programa VALUES ('search_X', 'd', 'search_X', 'd', 'L');
INSERT INTO programa VALUES ('search_X', 'e', 'search_X', 'e', 'L');
INSERT INTO programa VALUES ('search_X', 'f', 'search_X', 'f', 'L');
INSERT INTO programa VALUES ('search_X', 'g', 'search_X', 'g', 'L');
INSERT INTO programa VALUES ('search_X', 'h', 'search_X', 'h', 'L');
INSERT INTO programa VALUES ('search_X', 'i', 'search_X', 'i', 'L');
INSERT INTO programa VALUES ('search_X', 'j', 'search_X', 'j', 'L');
INSERT INTO programa VALUES ('search_X', 'k', 'search_X', 'k', 'L');
INSERT INTO programa VALUES ('search_X', 'l', 'search_X', 'l', 'L');
INSERT INTO programa VALUES ('search_X', 'm', 'search_X', 'm', 'L');
INSERT INTO programa VALUES ('search_X', 'n', 'search_X', 'n', 'L');
INSERT INTO programa VALUES ('search_X', 'o', 'search_X', 'o', 'L');
INSERT INTO programa VALUES ('search_X', 'p', 'search_X', 'p', 'L');
INSERT INTO programa VALUES ('search_X', 'q', 'search_X', 'q', 'L');
INSERT INTO programa VALUES ('search_X', 'r', 'search_X', 'r', 'L');
INSERT INTO programa VALUES ('search_X', 's', 'search_X', 's', 'L');
INSERT INTO programa VALUES ('search_X', 't', 'search_X', 't', 'L');
INSERT INTO programa VALUES ('search_X', 'u', 'search_X', 'u', 'L');
INSERT INTO programa VALUES ('search_X', 'v', 'search_X', 'v', 'L');
INSERT INTO programa VALUES ('search_X', 'w', 'search_X', 'w', 'L');
INSERT INTO programa VALUES ('search_X', 'x', 'search_X', 'x', 'L');
INSERT INTO programa VALUES ('search_X', 'y', 'search_X', 'y', 'L');
INSERT INTO programa VALUES ('search_X', 'z', 'search_X', 'z', 'L');
INSERT INTO programa VALUES ('search_X', 'X', 'load_next', 'X', 'L'); --CAMBIA DE ESTADO PARA VER SI ENCUENTRA OTRO CARACTER PARA COPIAR

INSERT INTO programa VALUES ('load_next', 'a', 'load_a', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'b', 'load_b', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'c', 'load_c', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'd', 'load_d', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'e', 'load_e', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'f', 'load_f', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'g', 'load_g', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'h', 'load_h', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'i', 'load_i', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'j', 'load_j', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'k', 'load_k', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'l', 'load_l', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'm', 'load_m', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'n', 'load_n', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'o', 'load_o', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'p', 'load_p', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'q', 'load_q', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'r', 'load_r', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 's', 'load_s', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 't', 'load_t', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'u', 'load_u', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'v', 'load_v', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'w', 'load_w', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'x', 'load_x', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'y', 'load_y', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'z', 'load_z', 'X', 'R');
INSERT INTO programa VALUES ('load_next', 'B', 'finish', 'B', 'R');
INSERT INTO programa VALUES ('load_next', 'X', 'load_next', 'X', 'L');

